---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-postgres-deploy
  labels:
    app: voting-postgres-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: db
          image: "postgres:latest"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres

