---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deploy
  labels:
    app: vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      labels:
        app: vote-app
    spec: 
      containers:
       - name: vote-container
         image: chi91/vote-image
         ports:
          - containerPort: 80
